name: Build UF2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  release:
    types: [created, published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: 'recursive'

      - name: Cache Pico SDK
        id: cache-pico-sdk
        uses: actions/cache@v4
        with:
          path: /home/runner/work/pico-sdk
          key: ${{ runner.os }}-pico-sdk-${{ hashFiles('**/pico_sdk_import.cmake') }}

      - name: Set up Pico SDK
        if: steps.cache-pico-sdk.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/raspberrypi/pico-sdk.git /home/runner/work/pico-sdk
          cd /home/runner/work/pico-sdk
          git submodule update --init

      - name: Set PICO_SDK_PATH
        run: echo "PICO_SDK_PATH=/home/runner/work/pico-sdk" >> $GITHUB_ENV

      - name: Install ARM GCC Compiler and CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi cmake

      - name: Build Firmware and stage for release
        run: |
          cd Firmware/LogicAnalyzer_V2
          mkdir build
          cd build
          cmake ..
          make
          mkdir -p ../../../release_assets
          cp LogicAnalyzer.uf2 ../../../release_assets/

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Build and Package Software
        working-directory: Software/LogicAnalyzer
        run: |
          VERSION="6.0.0.0"
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${{ github.ref_name }}"
          fi
          pwsh -Command "& { . ./publish.ps1 -packageVersion $VERSION }"
          mv ../Packages/* ../../release_assets/

      - name: Package Hardware Files
        run: |
          ./.github/workflows/package_hardware.sh
          mv hardware_packages/*.zip release_assets/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: release_assets/*

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release_assets/*
          tag: ${{ github.ref_name }}
          overwrite: true
          file_glob: true
